# Generated by Django 6.0.5 on 2026-05-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0003_kosh_head_percentage_delete_head_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(blank=True, max_length=200, null=True)),
                ('installment', models.CharField(blank=True, max_length=20, null=True)),
                ('release_order_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.financial_year')),
            ],
        ),
    ]
