# Generated by Django 6.0.5 on 2026-05-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0001_initial'),
        ('ZillaParishad', '0002_zilla_parishad_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund_release',
            old_name='fy',
            new_name='financial_year',
        ),
        migrations.AddField(
            model_name='fund_release',
            name='zp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZillaParishad.zilla_parishad_user'),
        ),
    ]
