# Generated by Django 6.0.5 on 2026-05-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0002_rename_fy_fund_release_financial_year_and_more'),
        ('ZillaParishad', '0002_zilla_parishad_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund_release',
            name='zp_user',
        ),
        migrations.AddField(
            model_name='fund_release',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_release_added_by', to='ZillaParishad.zilla_parishad_user'),
        ),
    ]
