# Generated by Django 6.0.5 on 2026-05-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0003_remove_fund_release_zp_user_fund_release_added_by'),
        ('Kosh', '0009_remove_kosh_user_kosh_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosh_Fund_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_date', models.DateField()),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Partially Used', 'Partially Used'), ('Fully Used', 'Fully Used'), ('Lapsed', 'Lapsed')], default='Allocated', max_length=30)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kosh_fund_allocations', to='FundRelease.fund_release')),
                ('kosh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='Kosh.kosh')),
            ],
            options={
                'verbose_name': 'Kosh Fund Allocation',
                'verbose_name_plural': 'Kosh Fund Allocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
