# Generated by Django 6.0.5 on 2026-05-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0004_kosh_fund_allocation'),
        ('Main', '0003_kosh_head_percentage_delete_head_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kosh_fund_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_allocations', to='FundRelease.kosh_fund_allocation')),
                ('kosh_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_allocations', to='Main.kosh_head')),
            ],
            options={
                'verbose_name': 'Head Allocation',
                'verbose_name_plural': 'Head Allocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
