# Generated by Django 6.0.5 on 2026-05-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0005_fund_release_fund_distributed_headallocation'),
        ('ZillaParishad', '0002_zilla_parishad_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_release',
            name='zilla_parishad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_releases', to='ZillaParishad.zilla_parishad'),
        ),
    ]
