# Generated by Django 6.0.5 on 2026-05-28 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0006_fund_release_zilla_parishad'),
        ('Kosh', '0009_remove_kosh_user_kosh_name'),
        ('Main', '0003_kosh_head_percentage_delete_head_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_release',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.financial_year'),
        ),
        migrations.AlterField(
            model_name='kosh_fund_allocation',
            name='fund_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_fund_allocations', to='FundRelease.fund_release'),
        ),
        migrations.AlterField(
            model_name='kosh_fund_allocation',
            name='kosh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_allocations', to='Kosh.kosh'),
        ),
    ]
