# Generated by Django 6.0.5 on 2026-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0007_alter_fund_release_financial_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headallocation',
            name='is_fund_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kosh_fund_allocation',
            name='is_fund_given',
            field=models.BooleanField(default=False),
        ),
    ]
