# Generated by Django 6.0.5 on 2026-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0008_headallocation_is_fund_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headallocation',
            name='freezed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='headallocation',
            name='lapsed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='kosh_fund_allocation',
            name='lapsed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
