# Generated by Django 6.0.5 on 2026-05-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0009_headallocation_freezed_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosh_fund_allocation',
            old_name='lapsed_amount',
            new_name='total_lapsed_amount',
        ),
    ]
