# Generated by Django 6.0.5 on 2026-05-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0010_rename_lapsed_amount_kosh_fund_allocation_total_lapsed_amount'),
        ('ZillaParishad', '0002_zilla_parishad_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosh_fund_allocation',
            name='distributed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_distributed_by', to='ZillaParishad.zilla_parishad_user'),
        ),
    ]
