# Generated by Django 6.0.5 on 2026-05-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundRelease', '0011_kosh_fund_allocation_distributed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosh_fund_allocation',
            name='allocated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
