# Generated by Django 6.0.5 on 2026-05-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PanchayatSamiti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GramPanchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gp_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('village_count', models.IntegerField(blank=True, default=1, null=True)),
                ('gp_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('sc_population', models.IntegerField(blank=True, null=True)),
                ('st_population', models.IntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('samiti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PanchayatSamiti.panchayatsamiti')),
            ],
        ),
        migrations.CreateModel(
            name='Kosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosh_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kosh_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_primary', models.BooleanField(blank=True, default=False, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Other', 'Other')], default='Savings', max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('GramPanchayat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kosh.grampanchayat')),
            ],
        ),
        migrations.CreateModel(
            name='KoshCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('President', 'President'), ('Secretary', 'Secretary'), ('Member', 'Member'), ('Treasurer', 'Treasurer')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Kosh_Committee_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Kosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kosh.kosh')),
            ],
        ),
        migrations.CreateModel(
            name='KoshUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Kosh_User_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Kosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kosh.kosh')),
            ],
        ),
    ]
