# Generated by Django 6.0.5 on 2026-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosh_user',
            name='kosh',
        ),
        migrations.AddField(
            model_name='kosh_user',
            name='kosh',
            field=models.ManyToManyField(blank=True, null=True, related_name='kosh_users', to='Kosh.kosh'),
        ),
    ]
