# Generated by Django 6.0.5 on 2026-05-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0001_initial'),
        ('PanchayatSamiti', '0002_alter_panchayatsamiti_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koshcommittee',
            old_name='password',
            new_name='kosh_name',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='GramPanchayat',
        ),
        migrations.RemoveField(
            model_name='koshcommittee',
            name='Kosh',
        ),
        migrations.RemoveField(
            model_name='koshcommittee',
            name='username',
        ),
        migrations.RemoveField(
            model_name='koshuser',
            name='Kosh',
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='samiti_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kosh',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kosh',
            name='gramPanchayat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kosh',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='koshuser',
            name='kosh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grampanchayat',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grampanchayat',
            name='samiti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gram_panchayats', to='PanchayatSamiti.panchayatsamiti'),
        ),
        migrations.AlterField(
            model_name='koshcommittee',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kosh',
            name='gramPanchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_accounts', to='Kosh.grampanchayat'),
        ),
        migrations.AddField(
            model_name='koshcommittee',
            name='kosh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='Kosh.kosh'),
        ),
        migrations.AddField(
            model_name='koshuser',
            name='kosh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_users', to='Kosh.kosh'),
        ),
    ]
