# Generated by Django 6.0.5 on 2026-05-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0002_rename_password_koshcommittee_kosh_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='gp_code',
            new_name='gram_panchayat_code',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='gp_name',
            new_name='gram_panchayat_name',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='gp_type',
            new_name='gram_panchayat_type',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='samiti',
            new_name='panchayat_samiti',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='samiti_name',
            new_name='panchayat_samiti_name',
        ),
    ]
