# Generated by Django 6.0.5 on 2026-05-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0002_remove_kosh_user_kosh_kosh_user_kosh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosh_population',
            name='gram_panchayat',
        ),
        migrations.AddField(
            model_name='kosh_population',
            name='kosh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_populations', to='Kosh.kosh'),
        ),
    ]
