# Generated by Django 6.0.5 on 2026-05-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0003_rename_gp_code_grampanchayat_gram_panchayat_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosh',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='opening_balance',
        ),
    ]
