# Generated by Django 6.0.5 on 2026-05-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0003_remove_kosh_population_gram_panchayat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosh',
            old_name='gramPanchayat',
            new_name='grampanchayat',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='panchayat_samiti_name',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='gramPanchayat_name',
        ),
    ]
