# Generated by Django 6.0.5 on 2026-05-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0004_rename_grampanchayat_kosh_grampanchayat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosh',
            name='grampanchayat',
        ),
        migrations.RemoveField(
            model_name='kosh_population',
            name='kosh',
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='panchayat_samiti_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kosh',
            name='gramPanchayat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kosh_population',
            name='gram_panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_populations', to='Kosh.grampanchayat'),
        ),
        migrations.AddField(
            model_name='kosh',
            name='gramPanchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh', to='Kosh.grampanchayat'),
        ),
    ]
