# Generated by Django 6.0.5 on 2026-05-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0004_remove_kosh_account_number_remove_kosh_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koshcommittee',
            name='role',
            field=models.CharField(blank=True, choices=[('Chairman', 'Chairman'), ('Member', 'Member')], max_length=50, null=True),
        ),
    ]
