# Generated by Django 6.0.5 on 2026-05-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0005_alter_koshcommittee_role'),
        ('Main', '0007_district_taluka'),
    ]

    operations = [
        migrations.CreateModel(
            name='GP_Cast_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='gram_panchayat_type',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='population',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='sc_population',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='st_population',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='village_count',
        ),
        migrations.AlterField(
            model_name='kosh',
            name='gramPanchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh', to='Kosh.grampanchayat'),
        ),
        migrations.CreateModel(
            name='GPPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cast_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_populations', to='Kosh.gp_cast_category')),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_populations', to='Main.financialyear')),
                ('gram_panchayat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_populations', to='Kosh.grampanchayat')),
            ],
        ),
        migrations.CreateModel(
            name='KoshBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosh_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('kosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='Kosh.kosh')),
            ],
        ),
    ]
