# Generated by Django 6.0.5 on 2026-05-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0005_remove_kosh_grampanchayat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosh',
            old_name='gramPanchayat',
            new_name='grampanchayat',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='panchayat_samiti_name',
        ),
        migrations.RemoveField(
            model_name='kosh',
            name='gramPanchayat_name',
        ),
        migrations.RemoveField(
            model_name='kosh_population',
            name='gram_panchayat',
        ),
        migrations.AddField(
            model_name='kosh_population',
            name='kosh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_populations', to='Kosh.kosh'),
        ),
        migrations.AlterField(
            model_name='kosh',
            name='kosh_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
