# Generated by Django 6.0.5 on 2026-05-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0006_rename_grampanchayat_kosh_grampanchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosh_bank_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kosh_bank_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], default='Active', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kosh_bank_detail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
