# Generated by Django 6.0.5 on 2026-05-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0006_gp_cast_category_remove_grampanchayat_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koshbankdetail',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='koshbankdetail',
            name='contact_phone',
        ),
    ]
