# Generated by Django 6.0.5 on 2026-05-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0007_remove_koshbankdetail_contact_person_and_more'),
        ('Main', '0008_super_user_rename_financialyear_financial_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KoshCommittee',
            new_name='Kosh_Committee',
        ),
        migrations.RemoveField(
            model_name='koshbankdetail',
            name='kosh',
        ),
        migrations.RemoveField(
            model_name='koshuser',
            name='kosh',
        ),
        migrations.CreateModel(
            name='Kosh_Bank_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosh_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('kosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_bank_details', to='Kosh.kosh')),
            ],
        ),
        migrations.RenameModel(
            old_name='GP_Cast_Category',
            new_name='Kosh_Cast_Category',
        ),
        migrations.CreateModel(
            name='Kosh_Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_count', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cast_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_populations', to='Kosh.kosh_cast_category')),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_populations', to='Main.financial_year')),
                ('gram_panchayat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_populations', to='Kosh.grampanchayat')),
            ],
        ),
        migrations.CreateModel(
            name='Kosh_Total_Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.BigIntegerField(blank=True, null=True)),
                ('tribal_population', models.BigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_total_populations', to='Main.financial_year')),
                ('kosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_total_populations', to='Kosh.kosh')),
            ],
        ),
        migrations.CreateModel(
            name='Kosh_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosh_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Kosh_User_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('is_retired', models.BooleanField(blank=True, default=False, null=True)),
                ('retired_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kosh_users', to='Kosh.kosh')),
            ],
        ),
        migrations.DeleteModel(
            name='GPPopulation',
        ),
        migrations.DeleteModel(
            name='KoshBankDetail',
        ),
        migrations.DeleteModel(
            name='KoshUser',
        ),
    ]
