# Generated by Django 6.0.5 on 2026-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0007_kosh_bank_detail_created_at_kosh_bank_detail_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grampanchayat',
            name='gram_panchayat_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
