# Generated by Django 6.0.5 on 2026-05-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosh', '0008_alter_grampanchayat_gram_panchayat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosh_user',
            name='kosh_name',
        ),
    ]
