# Generated by Django 6.0.5 on 2026-05-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_tenant_is_active_tenant_status_and_more'),
        ('ZillaParishad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zillaparishaduser',
            name='zilla_parishad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zillaparishad',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zillaparishad',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zilla_parishads', to='Main.department'),
        ),
        migrations.AlterField(
            model_name='zillaparishad',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zilla_parishads', to='Main.tenant'),
        ),
        migrations.AlterField(
            model_name='zillaparishaduser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zillaparishaduser',
            name='zilla_parishad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zp_users', to='ZillaParishad.zillaparishad'),
        ),
    ]
