# Generated by Django 6.0.5 on 2026-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZillaParishad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zilla_parishad_user',
            name='Role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
