# Generated by Django 6.0.5 on 2026-05-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZillaParishad', '0002_zillaparishaduser_zilla_parishad_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zillaparishad',
            old_name='department_name',
            new_name='zillaParishad_name',
        ),
        migrations.RenameField(
            model_name='zillaparishad',
            old_name='zp_code',
            new_name='zillaParishad_name_code',
        ),
        migrations.RemoveField(
            model_name='zillaparishad',
            name='department',
        ),
        migrations.RemoveField(
            model_name='zillaparishad',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='zillaparishad',
            name='zp_name',
        ),
    ]
