# Generated by Django 6.0.5 on 2026-05-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZillaParishad', '0003_rename_department_name_zillaparishad_zillaparishad_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zillaparishad',
            old_name='zillaParishad_name_code',
            new_name='zillaParishad_code',
        ),
        migrations.RemoveField(
            model_name='zillaparishad',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='zillaparishad',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='zillaparishad',
            name='contact_phone',
        ),
    ]
