# Generated by Django 6.0.5 on 2026-05-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanchayatSamiti', '0005_rename_panchayatsamiti_panchayat_samiti_and_more'),
        ('ZillaParishad', '0004_rename_zillaparishad_name_code_zillaparishad_zillaparishad_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZillaParishad',
            new_name='Zilla_Parishad',
        ),
        migrations.CreateModel(
            name='Zilla_Parishad_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zilla_parishad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='ZillaParishad_User_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('is_retired', models.BooleanField(blank=True, default=False, null=True)),
                ('retired_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('zilla_parishad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zp_users', to='ZillaParishad.zilla_parishad')),
            ],
        ),
        migrations.DeleteModel(
            name='ZillaParishadUser',
        ),
    ]
