# Generated by Django 6.0.5 on 2026-05-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_super_user_rename_financialyear_financial_year_and_more'),
        ('ZillaParishad', '0005_rename_zillaparishad_zilla_parishad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zilla_parishad',
            name='district_name',
        ),
        migrations.AddField(
            model_name='zilla_parishad',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zilla_parishads', to='Main.district'),
        ),
    ]
