# Generated by Django 6.0.5 on 2026-05-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
