# Generated by Django 6.0.5 on 2026-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_kosh_head_head_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosh_head',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Head_Percentage',
        ),
    ]
