# Generated by Django 6.0.5 on 2026-05-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_delete_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='Main.tenant'),
        ),
    ]
