# Generated by Django 6.0.5 on 2026-05-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_superuser'),
        ('ZillaParishad', '0003_rename_department_name_zillaparishad_zillaparishad_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
