# Generated by Django 6.0.5 on 2026-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_district_taluka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Super_User_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FinancialYear',
            new_name='Financial_Year',
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
