# Generated by Django 6.0.5 on 2026-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='success_story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
