# Generated by Django 6.0.5 on 2026-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_success_story_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_master',
            name='activity',
        ),
        migrations.AlterField(
            model_name='administrative_sanction',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
    ]
