# Generated by Django 6.0.5 on 2026-05-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_remove_work_master_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_in_progress',
            name='status',
        ),
    ]
