# Generated by Django 6.0.5 on 2026-05-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        ('ZillaParishad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchayat_Samiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zilla_parishad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('panchayat_samiti_name', models.CharField(blank=True, max_length=255, null=True)),
                ('panchayat_samiti_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samitis', to='Main.taluka')),
                ('zilla_parishad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samitis', to='ZillaParishad.zilla_parishad')),
            ],
        ),
        migrations.CreateModel(
            name='Panchayat_Samiti_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Panchayat_Samiti_User_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('is_retired', models.BooleanField(blank=True, default=False, null=True)),
                ('retired_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('panchayat_samiti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samiti_users', to='PanchayatSamiti.panchayat_samiti')),
            ],
        ),
    ]
