# Generated by Django 6.0.5 on 2026-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanchayatSamiti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat_samiti_user',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
