# Generated by Django 6.0.5 on 2026-05-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanchayatSamiti', '0001_initial'),
        ('ZillaParishad', '0002_zillaparishaduser_zilla_parishad_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panchayatsamiti',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='panchayatsamiti',
            name='zilla_parishad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samitis', to='ZillaParishad.zillaparishad'),
        ),
        migrations.AlterField(
            model_name='panchayatsamitiuser',
            name='PanchayatSamiti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samiti_users', to='PanchayatSamiti.panchayatsamiti'),
        ),
        migrations.AlterField(
            model_name='panchayatsamitiuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
