# Generated by Django 6.0.5 on 2026-05-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanchayatSamiti', '0002_alter_panchayatsamiti_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayatsamiti',
            old_name='samiti_code',
            new_name='panchayat_samiti_code',
        ),
        migrations.RenameField(
            model_name='panchayatsamiti',
            old_name='samiti_name',
            new_name='panchayat_samiti_name',
        ),
        migrations.RenameField(
            model_name='panchayatsamitiuser',
            old_name='PanchayatSamiti',
            new_name='panchayat_samiti',
        ),
    ]
