# Generated by Django 6.0.5 on 2026-05-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanchayatSamiti', '0002_panchayat_samiti_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayat_samiti',
            name='zilla_parishad_name',
        ),
    ]
