# Generated by Django 6.0.5 on 2026-05-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanchayatSamiti', '0003_remove_panchayat_samiti_zilla_parishad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat_samiti',
            name='zilla_parishad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
