# Generated by Django 6.0.5 on 2026-05-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_district_taluka'),
        ('PanchayatSamiti', '0003_rename_samiti_code_panchayatsamiti_panchayat_samiti_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayatsamiti',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='panchayatsamiti',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='panchayatsamiti',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='panchayatsamiti',
            name='taluka_name',
        ),
        migrations.AddField(
            model_name='panchayatsamiti',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samitis', to='Main.taluka'),
        ),
        migrations.AlterField(
            model_name='panchayatsamitiuser',
            name='panchayat_samiti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samiti_users', to='PanchayatSamiti.panchayatsamiti'),
        ),
    ]
