# Generated by Django 6.0.5 on 2026-05-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_super_user_rename_financialyear_financial_year_and_more'),
        ('PanchayatSamiti', '0004_remove_panchayatsamiti_contact_email_and_more'),
        ('ZillaParishad', '0004_rename_zillaparishad_name_code_zillaparishad_zillaparishad_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanchayatSamiti',
            new_name='Panchayat_Samiti',
        ),
        migrations.CreateModel(
            name='Panchayat_Samiti_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Panchayat_Samiti_User_Profile/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('is_retired', models.BooleanField(blank=True, default=False, null=True)),
                ('retired_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('panchayat_samiti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayat_samiti_users', to='PanchayatSamiti.panchayat_samiti')),
            ],
        ),
        migrations.DeleteModel(
            name='PanchayatSamitiUser',
        ),
    ]
